# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendita',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
